/**
 * Digital Archive Emigo App Server API
 * An interface to a for managing the database nodes
 *
 * OpenAPI spec version: 1.0.4
 * Contact: rosborne@coredb.org
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface SystemStat { 
    timestamp: number;
    processor: number;
    memory: number;
    storage: number;
    requests: number;
    accounts: number;
}
