-- MySQL Script generated by MySQL Workbench
-- Sun Apr 28 11:32:10 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema portal
-- -----------------------------------------------------


-- -----------------------------------------------------
-- Table `device`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `device` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(128) NOT NULL,
  `salt` VARCHAR(128) NOT NULL,
  `password` VARCHAR(128) NOT NULL,
  `address` VARCHAR(32) NOT NULL,
  `dns_status` VARCHAR(32) NOT NULL,
  `dns` VARCHAR(256) NULL,
  `port` INT(11) NOT NULL,
  `app` VARCHAR(32) NOT NULL,
  `created` INT(64) NOT NULL,
  `updated` INT(64) NOT NULL,
  `portal_token` VARCHAR(128) NOT NULL,
  `account_token` VARCHAR(128) NOT NULL,
  `access_token` VARCHAR(128) NOT NULL,
  `stat_token` VARCHAR(128) NOT NULL,
  `conf_token` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `portal_token_UNIQUE` (`portal_token` ASC),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `log` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `level` VARCHAR(32) NULL,
  `message` VARCHAR(4096) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `account` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `emigo_id` VARCHAR(64) NOT NULL,
  `device_id` INT NOT NULL,
  `salt` VARCHAR(128) NOT NULL,
  `password` VARCHAR(128) NOT NULL,
  `token` VARCHAR(128) NOT NULL,
  `created` INT(64) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `emigo_id_UNIQUE` (`emigo_id` ASC),
  CONSTRAINT `account_device`
    FOREIGN KEY (`device_id`)
    REFERENCES `device` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `token`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `token` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `emigo_id` VARCHAR(64) NULL,
  `device_id` INT NOT NULL,
  `token` VARCHAR(128) NOT NULL,
  `issued` INT(64) NOT NULL,
  `expires` INT(64) NOT NULL,
  `expired` TINYINT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `token_UNIQUE` (`token` ASC),
  CONSTRAINT `token_device`
    FOREIGN KEY (`device_id`)
    REFERENCES `device` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `system`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `stat` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `timestamp` INT(32) NOT NULL,
  `processor` INT NOT NULL,
  `memory` BIGINT(64) NOT NULL,
  `storage` BIGINT(64) NOT NULL,
  `requests` BIGINT(64) NOT NULL,
  `devices` BIGINT(64) NOT NULL,
  `accounts` BIGINT(64) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `config`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `config` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `config_id` VARCHAR(32) NOT NULL,
  `str_value` VARCHAR(1024) NULL,
  `num_value` BIGINT(64) NULL,
  `bool_value` TINYINT NULL,
  UNIQUE INDEX `config_id_UNIQUE` (`config_id` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

